### ISSUE TITLE
set TCP_NODELAY and TCP_QUICKACK to TRUE

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nethsm-sdk-rs#11]
This should improve the performance.

**Comment by robin-nitrokey** [comment]
Setting `TCP_NODELAY` can be done in `ureq` using [`AgentBuilder::no_delay`](https://docs.rs/ureq/latest/ureq/struct.AgentBuilder.html#method.no_delay).  `TCP_QUICKACK` is not supported AFAIS.

**Comment by ansiwen** [comment]
NODELAY must be set on the server side, which we do already. QUICKACK is not POSIX but mainly Linux, and must be set in the client side on _every_ write. Since we set NODELAY already on the server side, setting QUICKACK on Linux clients seems not necessary.

**Comment by robin-nitrokey** [comment]
Thanks for the explanation!  Then I’ll close the issue here.
