### ISSUE TITLE
Unable to use restore from backup due to missing authentication

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/nethsm-sdk-rs#15]
Hi! :wave: 

I'm using this crate in the [nethsm crate](https://crates.io/crates/nethsm) and noticed that one of the endpoints that reliably fails for me is the one for restoring from backup (I always get a 400 response code).

I have already reported this in the nethsm repository, please see https://github.com/Nitrokey/nethsm/issues/5 for further details.

In short, it appears as if authentication and authorization handling is missing in the relevant function:

https://github.com/Nitrokey/nethsm-sdk-rs/blob/569321d82d8717221b056cb96587ca42d4574e1c/src/apis/default_api.rs#L3353-L3401

Compare to:

https://github.com/Nitrokey/nethsm-sdk-rs/blob/569321d82d8717221b056cb96587ca42d4574e1c/src/apis/default_api.rs#L3300-L3349

I am tracking this issue downstream in https://gitlab.archlinux.org/archlinux/signstar/-/issues/8

**Comment by robin-nitrokey** [comment]
AFAIS this is caused by a missing `security` field for the restore endpoint in the API spec, so let’s continue the discussion in the NetHSM issue.

**Comment by robin-nitrokey** [comment]
This should now work both for the unauthenticated/complete restore and the authenticated/partial restore.  Please report back if there are still issues with it.

**Comment by dvzrv** [comment]
Oof, I was under the impression, that this has already been added in a released version of nethsm-sdk-rs.

I'm currently testing on the actual hardware but am still running into this issue unfortunately.

**Comment by dvzrv** [comment]
Alright, after using https://github.com/Nitrokey/nethsm-sdk-rs/commit/a88b46113c28466cceeed03862d37bf3a3fbd700 I am now able to do restore from backup on an already provisioned system.
However, for an unprovisioned system it does not yet work (still status code 400).

(I have sent test cases, wireshark dumps and shell logs out of band).

**Comment by robin-nitrokey** [comment]
AFAIS the unprovisioned case has now been fixed too so this is really resolved.
