### ISSUE TITLE
Multipart requests do not work

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nethsm-sdk-rs#20]
Multipart requests, for example in `default_api::system_restore_post`, are not implemented.

**Comment by wiktor-k** [comment]
:thinking: c7cbe7b74d69db328767489e2ab1b5e2fb31598c adds dependency on the `multipart` crate which is unmaintained for a year (see [RUSTSEC-2023-0050](https://rustsec.org/advisories/RUSTSEC-2023-0050)).

Would it be possible to use one of the alternatives listed there? (e.g. [multer](https://crates.io/crates/multer) or [multiparty](https://crates.io/crates/multiparty))

Thanks for your time! :wave:

**Comment by robin-nitrokey** [comment]
I’m aware of the problem but I don’t know a suitable replacement.  `multer` and `multipart` only support multipart decoding, not encoding.

**Comment by robin-nitrokey** [comment]
I’ve created https://github.com/Nitrokey/nethsm-sdk-rs/issues/29 to keep track of the issue.

**Comment by wiktor-k** [comment]
> I’m aware of the problem but I don’t know a suitable replacement. `multer` and `multiparty` only support multipart decoding, not encoding.

Oh, I see. I wonder what would be the effort of writing a limited scope encoder. I haven't checked the usages yet so this may be a very bad idea 😅

**Comment by robin-nitrokey** [comment]
It should not be that hard.  I just did not want to include it in this crate directly because I think it should be maintained and tested separately, and I did not want to do that myself unless there are concrete issues with `multipart` other than being unmaintained.  If you want to look into that, I’m happy to test and eventually migrate.

**Comment by wiktor-k** [comment]
Agreed. I'll check out if it makes sense to extend existing crates. Thanks for the explanation! 👋
