### ISSUE TITLE
Include API spec in repository

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nethsm-sdk-rs#23]
To make the code generation reproducible and to give the developer control over the API spec version that is used, it should be included in the repository instead of being pulled directly from nethsmdemo.nitrokey.com.

**Comment by jans23** [comment]
Which repository do you refer to? It is [here](https://github.com/Nitrokey/nethsm/blob/main/docs/nethsm-api.yaml) available and shouldn't be duplicated to other repositories IMO.

**Comment by robin-nitrokey** [comment]
I mean this repository.  For development, it is important to be able to generate the API client in a reproducible way.  For example, I am currently working on fixing https://github.com/Nitrokey/nethsm-sdk-rs/issues/20.  That requires changes to the API generator.  But the current main does not yet include the latest changes to the API spec.  So if I now run the code generator, it pulls in changes that are unrelated to the problem that I’m working on.

Also, having a local copy makes it possible to change the API spec for testing and development, or worst case to fix an incompatibility with the upstream API spec.

This is the same that we approach that we use for the Python SDK.  Adapting to changes in the API spec is a manual task anyway.  The API spec can be easily updated from upstream using the Makefile, for example: https://github.com/Nitrokey/nethsm-sdk-py/blob/54727badd888bb134a78f52fd7d217075f6e2a1a/Makefile#L51-L52

**Comment by jans23** [comment]
I see, that makes sense.
